### PR TITLE
Fix repository.url in package.json files.

### PR DESCRIPTION
**Pull request by zbigg**
See this conversation: https://github.com/heremaps/harp-font-resources/issues/25#issuecomment-492552436

### CODE REVIEW

**Comment by zbigg** [comment]
> After further reading, it is not needed. Both formats are accepted.

@musculman 
I'm not sure, https://docs.npmjs.com/files/package.json says

> The URL should be a publicly available (perhaps read-only) url that can be handed directly to a VCS program without any modification

`git` doesn't like current "url"s:

```
$ git clone git://github.com:heremaps/harp.gl.git
Cloning into 'harp.gl'...
fatal: Unable to look up github.com:heremaps (port 9418) (nodename nor servname provided, or not known)
```

I guess following would be acceptable:
```
"repository": "github:heremaps/harp.gl"
```
but that prevents us from having `directory`.

Nevertheless, proper URL is much better for interoperability so i would commit this

**Comment by musculman** [comment]
If you want to unify the formats, is fine, but we have examples of npm packages already published using the `:` that work fine.
I was wrong on my original comment on the issue in the harp-font-resources catalog, as both are accepted.

**Comment by zbigg** [comment]
@musculman TLDR - closing it

`https://www.npmjs.com/package/@here/harp-map-theme` also says `Unable to find a readme for @here/harp-map-theme@0.2.3`.

So, as we have this problems only with huuge packages (`@here/harp-font-resources`) and `harp-map-theme` i assume this is somehow connected with `npmjs` infra refusing to inspect these and extract README.md files.

Unfortunately, more people have problem like this [1] and seems like there is no resolution.

[1] https://npm.community/search?q=Unable%20to%20find%20a%20readme%20for

**Comment by musculman** [comment]
Thanks for the additional information, from my side I was also not able to find good reasons to change it either way or to investigate further :(

**Pull request closed without merging**
