### PR TITLE
Remove duplicate readdirp from the yarn lockfile.

### PR DESCRIPTION
**Pull request by robertoraggi**
yarn-deduplicated didn't remove this entry.

### CODE REVIEW

**Review by FraukeF — COMMENTED** [review]
It should not be removed as it is asking for a ~ version, not a ^  version,
so basically readdirp@~3.4.0 and readdirp@~3.5.0 have no overlapping version they can use, as the first has the scope of readdirp@~3.4.x and the second readdirp@~3.5.x

**Comment by FraukeF** [comment]
I just checked, its even more restringent https://github.com/npm/node-semver#tilde-ranges-123-12-1 ... so definitly no overlapping versions there :)

**Review by FraukeF — DISMISSED** [review]
As this is the removal of a unreferenced package and not as mentioned a duplicate one, approved

**Comment by robertoraggi** [comment]
> I just checked, its even more restringent https://github.com/npm/node-semver#tilde-ranges-123-12-1 ... so definitly no overlapping versions there :)

In this particular case the issue is that yarn-deduplicate removed all the reachable references to `readdirp@~3.4.0` but it left both `readdirp@~3.4.0` and `readdirp@~3.5.0` in the lockfile. So running `yarn` on a fresh build resulted in a modified yarn.lock file. So assuming that we want to keep using yarn deduplicate the workflow will be to run again `yarn` after `yarn deduplicate` to prune the lock file.

**Review by FraukeF — APPROVED** [review]

**Pull request merged**
