### PR TITLE
MINOR: Fixing malformed theme JSON files

### PR DESCRIPTION
**Pull request by SahinHERE**
* Fixed berlin_tilzen_base.json
 * Fixed berlin_tilezen_day_reduced.json

### CODE REVIEW

**Comment by zbigg** [comment]
Duplicate of #370

**Comment by SahinHERE** [comment]
Basically we did the same fix, I don`t care which commit gets in. Do you want me to cancel my commit?

**Comment by zbigg** [comment]
> Basically we did the same fix, I don`t care which commit gets in. Do you want me to cancel my commit?

I will cancel this, as it's farther in pipeline so with high probability we will wait longer fir CI to build it.

Nevertheless, thanks for taking care and ... sorry for problem, because it was me who broke these files.

**Comment by SahinHERE** [comment]
No worries, can happen to the best of us.

**Pull request closed without merging**
