### PR TITLE
Test optimized style processing

### PR DESCRIPTION
**Pull request by zbigg**
Don't review.

This is experiment with logging of decoding time for #853.

Compare results with #862.

### CODE REVIEW

**Comment by zbigg** [comment]
Decoders tests please

**Comment by zbigg** [comment]
Decoders tests please

**Comment by DimitryRd** [comment]
Decoders tests please

**Comment by DimitryRd** [comment]
Decoders tests please

**Comment by zbigg** [comment]
Superseded by #878

**Pull request closed without merging**
