### PR TITLE
MINOR: Filter techniques by $geometryType.

### PR DESCRIPTION
**Pull request by robertoraggi**
Classify the styling rules based on the requested geoemtry type, and
make use of requested $geometryType to filter the style conditions.

Signed-off-by: Roberto Raggi <roberto.raggi@here.com>

### CODE REVIEW

**Comment by robertoraggi** [comment]
@heremaps-bot Decoders test please

**Comment by DimitryRd** [comment]
Decoders test please

**Comment by DimitryRd** [comment]
GPU tests please

**Comment by DimitryRd** [comment]
GPU tests please Dmitry

**Comment by DimitryRd** [comment]
Decoders tests please

**Comment by DimitryRd** [comment]
GPU tests please

**Pull request merged**
