### PR TITLE
HARP-5950: Increase cache limit values

### PR DESCRIPTION
**Pull request by sasha240100**
Signed-off-by: Oleksandr Buzin <ext-oleksandr.buzin@here.com>

### CODE REVIEW

**Comment by sasha240100** [comment]
GPU test please

**Comment by sasha240100** [comment]
@DimitryRd @zellm Does this satisfy requirements?

**Comment by sasha240100** [comment]
rebuild please

**Comment by zellm** [comment]
rebuild please

**Comment by Astrak** [comment]
@heremaps-bot retest this please

**Comment by Astrak** [comment]
@heremaps-bot retest this please

**Pull request merged**
