### PR TITLE
HARP-5898: Update berlin_tilezen_base.json

### PR DESCRIPTION
**Pull request by adraksle**
HARP-5898: Adjustment of street & railway network for OpenSource scheme

### CODE REVIEW

**Comment by zellm** [comment]
@heremaps-bot ok to test

**Comment by amsgames94** [comment]
@heremaps-bot retest this please

**Comment by amsgames94** [comment]
@heremaps-bot retest this please

**Comment by amsgames94** [comment]
Changes will be applied in #495 .

**Pull request closed without merging**
