### PR TITLE
Change error message to warning to avoid confusion

### PR DESCRIPTION
**Pull request by ninok**

### CODE REVIEW

**Comment by ninok** [comment]
> I guess we need to also change the logger type for this isnt it? because this is also showing as error.
> `[browser] error: THREE.WebGLRenderer: Error creating WebGL context.`

This message is comming from three.js. They catch the exception, log it to the console and re-throw it:
https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L256

So there is nothing we can do about it.

**Comment by ninok** [comment]
@harpgl-bot retest this please

**Comment by ninok** [comment]
@harpgl-bot retest this please

**Comment by gairik** [comment]
> > I guess we need to also change the logger type for this isnt it? because this is also showing as error.
> > `[browser] error: THREE.WebGLRenderer: Error creating WebGL context.`
> 
> This message is comming from three.js. They catch the exception, log it to the console and re-throw it:
> https://github.com/mrdoob/three.js/blob/master/src/renderers/WebGLRenderer.js#L256
> 
> So there is nothing we can do about it.

`getWebGlInfo()` this itself is doing the work as well as logging. so we cannot do anything, like you mentioned. got it now.

**Pull request merged**
