### PR TITLE
OLPRPS-5209: Added HERE logo (watermark) to the bottom left corner of map

### PR DESCRIPTION
**Pull request by keaukraine**
OLPRPS-5209: Added HERE logo (watermark) to the bottom left corner of map canvas.

Signed-off-by: Oleksandr Popov <ext-oleksandr.popov@here.com>

### CODE REVIEW

**Comment by ninok** [comment]
Just a question about license: If we add the HERE logo into this repository, does it mean people can use and modify  it and use it toe somebody else. @tsteenbe Can you give advice here please.

**Comment by tsteenbe** [comment]
> Just a question about license: If we add the HERE logo into this repository, does it mean people can use and modify it and use it toe somebody else. @tsteenbe Can you give advice here please.

Do not add HERE brand logo to the bottom of the map but implement a generic attribution mechanism in harp.gl that allows setting a attribution link in the bottom right corner of the map. Then any npm package that add a new map to harp.gl can define the needed attribution.

**Comment by ninok** [comment]
> Do not add HERE brand logo to the bottom of the map but implement a generic attribution mechanism in harp.gl that allows setting a logo with link in the bottom right corner of the map. Then any npm package that add a new map to harp.gl can define the needed a logo.
This we have in a separate PR #911. This PR can just be abandoned.

**Comment by keaukraine** [comment]
After consulting with @ninok decided to abandon this PR.

**Pull request closed without merging**
