### PR TITLE
HARP-12247 Handle geometry without index buffer / feature starts

### PR DESCRIPTION
**Pull request by nzjony**

### CODE REVIEW

**Comment by nzjony** [comment]
@harpgl-bot retest this please

**Review by robertoraggi — DISMISSED** [review]

**Comment by nzjony** [comment]
@harpgl-bot retest this please

**Review by robertoraggi — APPROVED** [review]

**Review by FraukeF — APPROVED** [review]

**Review by FraukeF — COMMENTED** [review]
Not really related, but I was just wondering, why this code lives in MapView.ts, do you know if theres a good reason, maybe we could move it to some TileObjectRenderer or something like that with the related classes, to get MapView slimmer and more focussed?

**Comment by nzjony** [comment]
> Not really related, but I was just wondering, why this code lives in MapView.ts, do you know if theres a good reason, maybe we could move it to some TileObjectRenderer or something like that with the related classes, to get MapView slimmer and more focussed?

@FraukeF , I completely agree. I think everything under `renderTileObjects` could be moved to some class as you say. I will create a ticket.

**Review by FraukeF — APPROVED** [review]

**Pull request merged**
