### PR TITLE
MINOR: Add dynamic markers example.

### PR DESCRIPTION
**Pull request by atomicsulfate**
Public example to show how to render pickable markers (icon&text) from dynamically generated GeoJSON points using FeatureDataSource.

### CODE REVIEW

**Comment by atomicsulfate** [comment]
macbook tests please

**Review by FraukeF — COMMENTED** [review]
Looks good to me, but I think it should move to the "Markers" section: 

markers_dynamic.ts

or something similar

**Comment by atomicsulfate** [comment]
@harpgl-bot retest this please

**Review by FraukeF — APPROVED** [review]

**Comment by atomicsulfate** [comment]
@harpgl-bot retest this please

**Comment by atomicsulfate** [comment]
@harpgl-bot retest this please

**Review by FraukeF — APPROVED** [review]

**Pull request merged**
