### PR TITLE
HARP-10772: Finish PickListener results explicitely.

### PR DESCRIPTION
**Pull request by atomicsulfate**
Signed-off-by: Andres Mandado <andres.mandado-almajano@here.com>

Thank you for contributing to harp.gl!

Before requesting a pull request, please remember to check the following documents:
* [contribution guidelines](https://github.com/heremaps/harp.gl/blob/master/CONTRIBUTING.md)
* [coding style](https://github.com/heremaps/harp.gl/blob/master/CODINGSTYLE.md)

If you are adding new functionality we would highly appreciate if you can describe what is the capability you are adding and even better if you can add some examples. Please also remember to add tests for it.

# CI Check

Our bots will check whether your PR can be directly integrated into the mainline. We have some internal integration tests running on the background, our bots will inform you of the next steps and someone from our team will take a look and help if needed!

And please do not forget to sign-off your commit! You can read more about DCO [here](https://julien.ponge.org/blog/developer-certificate-of-origin-versus-contributor-license-agreements/). But, in short, you just need to use `git commit -s` or append `--signoff` when you are committing to the repo.

Happy contributing!

### CODE REVIEW

**Comment by atomicsulfate** [comment]
> Why do you make it now mandatory to call results explicity instead of having it as part of the call to `results` ?

It was precisely a review comment from Nino in a previous PR requesting this. I agree that side effects in a getter are unexpected.

**Comment by nzjony** [comment]
> > Why do you make it now mandatory to call results explicity instead of having it as part of the call to `results` ?
> 
> It was precisely a review comment from Nino in a previous PR requesting this. I agree that side effects in a getter are unexpected.

True, but such side effects aren't visible to the external users through the existing interface?

**Comment by atomicsulfate** [comment]
> > > Why do you make it now mandatory to call results explicity instead of having it as part of the call to `results` ?
> > 
> > 
> > It was precisely a review comment from Nino in a previous PR requesting this. I agree that side effects in a getter are unexpected.
> 
> True, but such side effects aren't visible to the external users through the existing interface?

The call to the getter potentially changes the state of PickListener  (set m_sorted to true). The caller cannot know this state change happened. Of course the getter documentation may give that hint, but it's still something unexpected a priori.

**Comment by nzjony** [comment]
`m_sorted` is private. Even if `results` sorts the internal results, any user of this class can't observe what the state was before, and therefore can't prove that any side effect happened. The only observable side affect is that the `sortResults` method is a bit slower.

**Comment by atomicsulfate** [comment]
> `m_sorted` is private. Even if `results` sorts the internal results, any user of this class can't observe what the state was before, and therefore can't prove that any side effect happened. The only observable side affect is that the `sortResults` method is a bit slower.

So you say that it's ok that the getter changes the private state of the object as long as there are no observable side effects.
Mind you, those side effects are actually observable: you add 2 results, then call the getter and you get just 1 (because maxResultCount was 1). 
But I see your point, as well as Nino's. I think any further discussion about this is not gonna be productive, it's hard to determine objectively what's the best option.
I'm good with how the code is right now. Unless @ninok cares to follow-up the discussion, I'll abandon this change since there's no consensus.

**Comment by ninok** [comment]
> I'm good with how the code is right now. Unless @ninok cares to follow-up the discussion, I'll abandon this change since there's no consensus.

@nzjony I don't get your point. Yes, the side effect is not observable from the outside, but from the inside. I mean in the future this class might change and some methods could access `m_results` directly and some use `results`.
Why would you want to hide the fact, that there is some finalization step after all picking results are collected?

**Comment by nzjony** [comment]
> Mind you, those side effects are actually observable: you add 2 results, then call the getter and you get just 1 (because maxResultCount was 1).

This I missed, good point. I would argue however that the user of this class can't know if the `addResult` or `results` method causes this behaviour, at least I can't think of a unit test where the side affect is observable.

**Comment by nzjony** [comment]
> @nzjony I don't get your point. Yes, the side effect is not observable from the outside, but from the inside. I mean in the future this class might change and some methods could access `m_results` directly and some use `results`.
> Why would you want to hide the fact, that there is some finalization step after all picking results are collected?

@ninok , I see your point now, thanks. I would hope that anyone changing this would make a unit test to check their assumptions to avoid such regressions.

I would hide it for the fact that adding an extra method makes it more difficult / error prone to use, I would suggest then to either:

- change `results` to `sortedResults`, so it is clear that `this.m_results` != `results`. OR
- apply the sort after each `addResult`, sorting an already sorted list is (probably) quite quick, and we are talking less than 50 items right, so this is probably good enough (especially considering this happens when the map is not moving, so performance is unlikely to be a huge concern)

But this is more my personal opinion than a strong recommendation, so I won't veto this going through.

**Pull request merged**
